const { generateTaskPlan } = require('../services/claudeService');

/**
 * POST /api/chat
 * Body: { message: string }
 * Returns the JSON plan generated by Claude.
 */
const chat = async (req, res) => {
  const { message } = req.body;

  // ── Input validation ───────────────────────────────────────────────────────
  if (!message || typeof message !== 'string') {
    return res.status(400).json({
      success: false,
      error: '`message` is required and must be a non-empty string.',
    });
  }

  const trimmed = message.trim();
  if (trimmed.length === 0) {
    return res.status(400).json({
      success: false,
      error: '`message` must not be blank.',
    });
  }

  if (trimmed.length > 2000) {
    return res.status(400).json({
      success: false,
      error: '`message` must be 2000 characters or fewer.',
    });
  }

  // ── Claude call ────────────────────────────────────────────────────────────
  try {
    const plan = await generateTaskPlan(trimmed);

    return res.status(200).json({
      success: true,
      data: plan,
    });
  } catch (err) {
    console.error('[ChatController] Claude error:', err.message);

    // Bad JSON from Claude
    if (err.rawOutput !== undefined) {
      return res.status(502).json({
        success: false,
        error: 'Claude returned an unexpected response format.',
        ...(process.env.NODE_ENV !== 'production' && { raw: err.rawOutput }),
      });
    }

    // Missing API key or auth failure
    if (err.status === 401 || err.message?.includes('API_KEY')) {
      return res.status(500).json({
        success: false,
        error: 'Server misconfiguration: missing or invalid Anthropic API key.',
      });
    }

    // Anthropic rate limit
    if (err.status === 429) {
      return res.status(429).json({
        success: false,
        error: 'Rate limit reached. Please wait a moment and try again.',
      });
    }

    // Anthropic overloaded / upstream error
    if (err.status >= 500) {
      return res.status(502).json({
        success: false,
        error: 'Claude API is currently unavailable. Please try again later.',
      });
    }

    // Catch-all
    return res.status(500).json({
      success: false,
      error: process.env.NODE_ENV === 'production' ? 'Internal server error.' : err.message,
    });
  }
};

module.exports = { chat };
